AttendanceWebApp/AttendanceWebApp/Controllers/LogsController.cs
using AttendanceWebApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AttendanceWebApp.Controllers
{
    public class LogsController : Controller
    {
        // GET: Logs
        public ActionResult Index(int? id)
        {
            using (var db = new ProjectEntities())
            {
                Attendance attendance = new Attendance();
                var getDate = DateTime.Now.ToLongDateString();
                var getCurrent = db.Attendances.Include(a => a.Course).Include(a => a.Student).Where(a => a.date == getDate && a.courseID == id);
                return View(getCurrent.ToList());
            } 
        }

        [HttpGet]
        public ActionResult SignAttendance()
        { 
            return View();
        }

        [HttpPost]
        public ActionResult SignAttendance(int? id, Student student, Attendance token)
        {
            
            using (var _context = new ProjectEntities())
            {
                Attendance attendance = new Attendance(); 
                string getCurrentDate = DateTime.Now.ToLongDateString();
                var getCourse = _context.Courses.Where(c => c.courseID == id).FirstOrDefault();
                var getStudentMatric = _context.Students.Where(s => s.student_matric_number == student.student_matric_number).FirstOrDefault();
                var getPassword = _context.PasswordTokens.Where(p => p.password_token == token.Course.PasswordToken.password_token).FirstOrDefault();

                if (getStudentMatric == null || getPassword == null)
                {
                    ViewData["Wrong Details"] = "Invalid Matric Number or Password Provided, please try again!!!";
                }
                else
                {
                    var getstdid = _context.CourseRegs.Where(p => p.Student.studentID == getStudentMatric.studentID).FirstOrDefault();
                    var getStudentID = _context.Attendances.Where(a => a.studentID == getStudentMatric.studentID).FirstOrDefault();
                    var getpassWordTime = _context.PasswordTokens.Where(p => p.password_token == getPassword.Course.PasswordToken.password_token).Select(p => p.time).FirstOrDefault();
                    var getServerTime = DateTime.Now.ToShortTimeString();
                    var courseIdComparison = _context.Attendances.Where(a => a.date == getCurrentDate && a.studentID == getstdid.studentID).Select(a => a.courseID).FirstOrDefault();
                    var numberOftimesStudentSignedInPreviously = _context.Attendances.Where(s => s.courseID == id && s.studentID == getstdid.studentID).GroupBy(g => g.studentID).Select(g => new { Studentrep = g.Key, StudentCount = g.Count() }).OrderBy(g => g.Studentrep);
                    int CountnumberOftimesStudentSignedInPreviously = numberOftimesStudentSignedInPreviously.Where(l => l.Studentrep == getstdid.studentID).Select(l => l.StudentCount).FirstOrDefault();
                    TimeSpan passwordTime = Convert.ToDateTime(getServerTime) - Convert.ToDateTime(getpassWordTime);

                    //if student not registered
                    if (getstdid == null)
                    {
                        ViewData["Unregistered"] = "Sorry, you cannot sign the attendance form for this course as You are not Registered for this course";
                    }
                    //Student registered and registering for the first time
                    if (getstdid != null && getStudentID == null)
                    {
                        //number of times student has signed in before
                        CountnumberOftimesStudentSignedInPreviously = 1; // student is signing for first time

                        if (passwordTime.TotalMinutes >= 5) //if time limit exceeds 5 minutes
                        {
                            ViewData["Time Expired"] = "Sorry, Cannot Sign in as Time expired!";
                        }
                        else
                        {
                            if (CountnumberOftimesStudentSignedInPreviously == 0)
                            {
                                CountnumberOftimesStudentSignedInPreviously = 1;
                            }
                            int percentage = (int)Math.Round((double)(100 * CountnumberOftimesStudentSignedInPreviously) / getCourse.number_of_days);
                            attendance.courseID = getCourse.courseID;
                            attendance.studentID = getStudentMatric.studentID;
                            attendance.attendance_percentage = percentage.ToString() + "%";
                            attendance.date = DateTime.Now.ToLongDateString();
                            _context.Attendances.Add(attendance);
                            _context.SaveChanges();
                            return RedirectToAction("StudentOwnAttendanceLogs", new { id = getstdid.studentID });
                        }

                    }
                    else if (getstdid != null && getStudentID.date != getCurrentDate)// if student registered and signed courses attendance before
                    {
                        if (passwordTime.TotalMinutes >= 5)
                        {
                            ViewData["Time Expired"] = "Sorry, Cannot Sign in as Time expired!";
                        }
                        else
                        {
                            if (CountnumberOftimesStudentSignedInPreviously == 0)
                            {
                                CountnumberOftimesStudentSignedInPreviously = 1;
                            }

                            int percentage = (int)Math.Round((double)(100 * CountnumberOftimesStudentSignedInPreviously) / getCourse.number_of_days);
                            attendance.courseID = getCourse.courseID;
                            attendance.studentID = getStudentMatric.studentID;
                            attendance.attendance_percentage = percentage.ToString() + "%";
                            attendance.date = DateTime.Now.ToLongDateString();
                            _context.Attendances.Add(attendance);
                            _context.SaveChanges();
                            return RedirectToAction("StudentOwnAttendanceLogs", new { id = getstdid.studentID });
                        }

                    }
                    else if (getstdid != null && getStudentID.date == getCurrentDate && courseIdComparison != id)
                    {
                        if (passwordTime.TotalMinutes >= 5)
                        {
                            ViewData["Time Expired"] = "Sorry, Cannot Sign in as Time expired!";
                        }
                        else
                        {
                            if (CountnumberOftimesStudentSignedInPreviously == 0)
                            {
                                CountnumberOftimesStudentSignedInPreviously = 1;
                            }

                            int percentage = (int)Math.Round((double)(100 * CountnumberOftimesStudentSignedInPreviously) / getCourse.number_of_days);
                            attendance.courseID = getCourse.courseID;
                            attendance.studentID = getStudentMatric.studentID;
                            attendance.attendance_percentage = percentage.ToString() + "%";
                            attendance.date = DateTime.Now.ToLongDateString();
                            _context.Attendances.Add(attendance);
                            _context.SaveChanges();
                            return RedirectToAction("StudentOwnAttendanceLogs", new { id = getstdid.studentID });
                        }
                    }
                    else if (getstdid != null && getStudentID.date == getCurrentDate && courseIdComparison == id)// if student registered and signed course attendance for that day
                    {
                        ViewData["Sign Once"] = "Sorry, can only sign once";
                    }
                }
                  
            }
            return View();
        } 

        public ActionResult StudentOwnAttendanceLogs(int? id)
        {
            ProjectEntities db = new ProjectEntities();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = new Attendance();
            var getLastAttendanceValue = db.Attendances.Where(a => a.studentID == id).ToList().Last();
            var getStudentAttendanceLogs = db.Attendances.Where(a => a.attendance_percentage == getLastAttendanceValue.attendance_percentage && a.studentID == id).ToList();
            
            if (attendance == null)
            {
                return HttpNotFound();
            }
            return View(getStudentAttendanceLogs);
        }
    }
}

AttendanceWebApp/AttendanceWebApp/Controllers/StaffController.cs
using AttendanceWebApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using QRCoder;
using MessagingToolkit.QRCode.Codec;
using MessagingToolkit.QRCode.Codec.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net;

namespace AttendanceWebApp.Controllers
{
    public class StaffController : Controller
    {
        private ProjectEntities db = new ProjectEntities();
        // GET: Staff
        public ActionResult Index()
        {
            Course course = new Course();
            IEnumerable<LecturerReg> similar = db.LecturerRegs.ToList();
            ViewBag.getSimilar = similar;
            return View(course);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Lecturer lecturer)
        {
            using (var db = new ProjectEntities())
            {
                var staffVerification = db.Lecturers.Where(l => l.lecturer_email == lecturer.lecturer_email 
                && l.lecturer_password == lecturer.lecturer_password).FirstOrDefault(); 
                if (staffVerification != null)
                {
                    Session["Name"] = staffVerification.lecturer_name.ToString();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect Email or Password!!");
                }
                return View();
            }
        }
         

        public ActionResult GeneratePassword(PasswordToken passwordToken, int? id)
        {

            string password = Membership.GeneratePassword(8, 2);
            string currentTime = DateTime.Now.ToLongTimeString();
            string currentDate = DateTime.Now.ToLongDateString();
            
            using (var _context = new ProjectEntities())
            {
                Course course = new Course();
                var getCourseID = _context.Courses.Where(c => c.courseID == id).FirstOrDefault();
                passwordToken.password_token = password;
                passwordToken.time = currentTime;
                passwordToken.date = currentDate;
                passwordToken.courseID = getCourseID.courseID;
                getCourseID.passwordID = passwordToken.passwordID;
                _context.Entry(getCourseID).State = EntityState.Modified;
                _context.PasswordTokens.Add(passwordToken);
                _context.SaveChanges();
                ViewData["GeneratedPassword"] = getCourseID.PasswordToken.password_token.ToString();
                return RedirectToAction("Index");
            }
           // return View();
        }

        //GET: Staff/GenerateQrCode/id
        public ActionResult GenerateQrCode(int? id)
        {
            using (var db = new ProjectEntities())
            { 
                var index = db.Courses.Where(c => c.courseID == id).FirstOrDefault();
                if (index != null)
                {
                    string pageUrl = "http://localhost:59524/Logs/SignAttendance/" + id;
                    QRCodeEncoder codeEncoder = new QRCodeEncoder();
                    Bitmap bitmap = codeEncoder.Encode(pageUrl);
                    bitmap.Save($"C:\\Users\\odigietony\\source\\repos\\AttendanceWebApp\\AttendanceWebApp\\QrImage\\{index.courseID}.jpg" ,ImageFormat.Jpeg);
                    var QrImage = Url.Content($"~/QrImage/{index.courseID}.jpg");
                    ViewData["QrImage"] = QrImage;
                }
                return View("GenerateQrCode");
            } 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }


}

AttendanceWebApp/AttendanceWebApp/Views/Staff/GeneratePassword.cshtml
@model AttendanceWebApp.Models.Course

@{
    ViewBag.Title = "GeneratePassword";
}

<h2>GeneratePassword</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.course_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.number_of_days)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.number_of_days)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordToken.password_token)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordToken.password_token)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.courseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AttendanceWebApp/AttendanceWebApp/Views/Staff/GenerateQrCode.cshtml
@model IEnumerable<AttendanceWebApp.Models.Course>
@{
    ViewBag.Title = "GenerateQrCode";
}



<div class="container mt-5 pt-5 d-flex justify-content-center align-items-md-center">
   
    <div class="row mt-5 pt-5 d-flex justify-content-center align-items-md-center">
        <h2 class="col-md-12">GenerateQrCode</h2>
        <div class="text-center mt-5">
            <img class="img-fluid" src="@(ViewData["QrImage"])" alt="Qr Code Image" style="width:15rem; height:15rem;"/>
        </div>
    </div>

</div>

AttendanceWebApp/AttendanceWebApp/Views/Staff/Index.cshtml
@model AttendanceWebApp.Models.Course
@using AttendanceWebApp.Models

@{
    ViewBag.Title = "Index";
    IEnumerable<LecturerReg> similar = ViewBag.getSimilar;
}

<div class="view">
    <div class="mt-5 pt-5 d-flex justify-content-center align-content-center">
        <h4> Welcome, @Session["Name"]</h4>
    </div>
    <div class="container d-flex justify-content-center align-content-center">
        @if (Session["Name"] != null)
        {


            <table class="table table-bordered dataTables_length bs-select" id="dtBasicExample">
                <thead>
                    <tr class="white-text">
                        <th>
                            @Html.DisplayNameFor(model => model.course_code)
                            <i class="ui-sortable-column-icon fa fa-fw fa-sort fa-sort-asc"></i>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.course_title)
                            <i class="ui-sortable-column-icon fa fa-fw fa-sort fa-sort-asc"></i>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.number_of_days)
                            <i class="ui-sortable-column-icon fa fa-fw fa-sort fa-sort-asc"></i>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PasswordToken.password_token)
                            <i class="ui-sortable-column-icon fa fa-fw fa-sort fa-sort-asc"></i>
                        </th>
                        <th class="white-text">Operations</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in similar)
                    {
                        if (item.Lecturer.lecturer_name == Session["Name"].ToString())
                        {
                            <tr class="white-text">

                                <td>
                                    @Html.DisplayFor(modelItem => item.Course.course_code)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Course.course_title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Course.number_of_days)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Course.PasswordToken.password_token)
                                </td>
                                <td>
                                    @Html.ActionLink("View Attendance", "Index", "Logs", new { id = item.Course.courseID }, new { @style = "color:#ffffff" }) |
                                    @Html.ActionLink("Generate Password", "GeneratePassword", new { id = item.Course.courseID }, new { @style = "color:#ffffff" }) |
                                    @Html.ActionLink("Generate QR Code", "GenerateQrCode", new { id = item.Course.courseID }, new { @style = "color:#ffffff" })
                                </td>
                            </tr>
                        }

                    }
                </tbody>
            </table>
        }
    </div>
</div>
    @section Scripts{
        <script type="text/javascript">
        $(document).ready(function () {
            $('#dtBasicExample').DataTable();
            $('.dataTables_length').addClass('bs-select');
        });
        </script>
    }

AttendanceWebApp/AttendanceWebApp/Views/Staff/Login.cshtml
@model AttendanceWebApp.Models.Lecturer

@{
    ViewBag.Title = "Login";
}


<div class="container mt-5 pt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card animated bounceInDown delay-3s" style="width: 30rem; height: 25rem;">
            <div class="card-header text-dark">
                <h2>Staff Login</h2>
            </div>
            <div class="card-body mt-5">
                <div class="card-text  text-dark">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">  
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group  d-flex align-content-center justify-content-lg-center">
                                @Html.LabelFor(model => model.lecturer_email, htmlAttributes: new { @class = "control-label " })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.lecturer_email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.lecturer_email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group  d-flex align-content-center justify-content-lg-center">
                                @Html.LabelFor(model => model.lecturer_password, htmlAttributes: new { @class = "control-label " })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.lecturer_password, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.lecturer_password, "", new { @class = "text-danger" })
                                </div>
                            </div> 
                                <div class="form-group d-flex justify-content-center align-items-center">
                                    <input type="submit" value="Login" class="btn btn-sm btn-dark-green" />
                                </div> 
                        </div>
                    }
                    
                </div>
            </div>
        </div>
    </div>
</div>