AttendanceWebApp/AttendanceWebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AttendanceWebApp.Models;

namespace AttendanceWebApp.Controllers
{
    public class AdminController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            if (ModelState.IsValid)
            {
                using (var db = new ProjectEntities())
                {
                    var adminDetails = db.Admins.Where(a => a.username == admin.username && a.password == admin.password).FirstOrDefault();
                    if (adminDetails != null)
                    {
                        return RedirectToAction("Index");
                    }
                }  
            }
            return View(admin);
        }

        [HttpGet]
        public ActionResult StaffList()
        {
            using (var db = new ProjectEntities())
            {
                return View(db.Lecturers.ToList());
            }  
        }

        [HttpGet]
        public ActionResult StaffRegistration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StaffRegistration(Lecturer lecturer)
        {
            using (var _context = new ProjectEntities() )
            {
                if (ModelState.IsValid)
                {
                    _context.Lecturers.Add(lecturer);
                    _context.SaveChanges();
                    return RedirectToAction("StaffList");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Students()
        {
            using (var db = new ProjectEntities())
            {
                return View(db.Students.ToList());
            }   
        }

        [HttpGet]
        public ActionResult StudentRegistration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StudentRegistration(Student student)
        {
            using (var _context = new ProjectEntities())
            {
                if (ModelState.IsValid)
                {
                    _context.Students.Add(student);
                    _context.SaveChanges();
                    return RedirectToAction("Students");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Courses()
        {
            using (var db = new ProjectEntities())
            {
                return View(db.Courses.ToList());
            }
        }

        [HttpGet]
        public ActionResult CourseCreation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CourseCreation(Course course)
        {
            using (var _context = new ProjectEntities())
            {
                if (ModelState.IsValid)
                {
                    _context.Courses.Add(course);
                    _context.SaveChanges();
                    return RedirectToAction("Courses");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult CourseRegList()
        {
            using (var db = new ProjectEntities())
            {
                var courseRegs = db.CourseRegs.Include(c => c.Course).Include(c => c.Student);
                return View(courseRegs.ToList());
            }
        }

        [HttpGet]
        public ActionResult CourseReg()
        {
            using (var db = new ProjectEntities())
            {
                ViewBag.courseID = new SelectList(db.Courses.ToList(), "courseID", "course_title");
                ViewBag.studentID = new SelectList(db.Students.ToList(), "studentID", "student_name");
                return View();
            }
        }

        [HttpPost]
        public ActionResult CourseReg(CourseReg courseReg)
        {
            using (var _context = new ProjectEntities())
            {
                if (ModelState.IsValid)
                {
                    _context.CourseRegs.Add(courseReg);
                    _context.SaveChanges();
                    return RedirectToAction("CourseRegList");
                }
                ViewBag.courseID = new SelectList(_context.Courses.ToList(), "courseID", "course_title", courseReg.courseID);
                ViewBag.studentID = new SelectList(_context.Students.ToList(), "studentID", "student_name", courseReg.studentID);
                return View(courseReg);
            }
           // return View(courseReg);
        }

        [HttpGet]
        public ActionResult LecturerRegList()
        {
            using (var db = new ProjectEntities())
            {
                return View(db.LecturerRegs.Include(c => c.Course).Include(s => s.Lecturer).ToList());
            }
        }

        [HttpGet]
        public ActionResult LecturerReg()
        {
            using (var db = new ProjectEntities())
            {
                ViewBag.courseID = new SelectList(db.Courses.ToList(), "courseID", "course_title");
                ViewBag.lecturerID = new SelectList(db.Lecturers.ToList(), "lecturerID", "lecturer_name");
                return View();
            }
        }

        [HttpPost]
        public ActionResult LecturerReg(LecturerReg lecturerReg)
        {
            using (var _context = new ProjectEntities())
            {
                if (ModelState.IsValid)
                {
                    _context.LecturerRegs.Add(lecturerReg);
                    _context.SaveChanges();
                    return RedirectToAction("LecturerRegList");
                }
                ViewBag.courseID = new SelectList(_context.Courses.ToList(), "courseID", "course_title");
                ViewBag.lecturerID = new SelectList(_context.Lecturers.ToList(), "lecturerID", "lecturer_name");
            }
            return View();
        }
 
    }
}

AttendanceWebApp/AttendanceWebApp/Controllers/StaffController.cs
using AttendanceWebApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using QRCoder;
using MessagingToolkit.QRCode.Codec;
using MessagingToolkit.QRCode.Codec.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net;

namespace AttendanceWebApp.Controllers
{
    public class StaffController : Controller
    {
        private ProjectEntities db = new ProjectEntities();
        // GET: Staff
        public ActionResult Index()
        {
            Course course = new Course();
            IEnumerable<LecturerReg> similar = db.LecturerRegs.ToList();
            ViewBag.getSimilar = similar;
            return View(course);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Lecturer lecturer)
        {
            using (var db = new ProjectEntities())
            {
                var staffVerification = db.Lecturers.Where(l => l.lecturer_email == lecturer.lecturer_email 
                && l.lecturer_password == lecturer.lecturer_password).FirstOrDefault(); 
                if (staffVerification != null)
                {
                    Session["Name"] = staffVerification.lecturer_name.ToString();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect Email or Password!!");
                }
                return View();
            }
        }
         

        public ActionResult GeneratePassword(PasswordToken passwordToken, int? id)
        {

            string password = Membership.GeneratePassword(8, 2);
            string currentTime = DateTime.Now.ToLongTimeString();
            string currentDate = DateTime.Now.ToLongDateString();
            
            using (var _context = new ProjectEntities())
            {
                Course course = new Course();
                var getCourseID = _context.Courses.Where(c => c.courseID == id).FirstOrDefault();
                passwordToken.password_token = password;
                passwordToken.time = currentTime;
                passwordToken.date = currentDate;
                passwordToken.courseID = getCourseID.courseID;
                getCourseID.passwordID = passwordToken.passwordID;
                _context.Entry(getCourseID).State = EntityState.Modified;
                _context.PasswordTokens.Add(passwordToken);
                _context.SaveChanges();
                ViewData["GeneratedPassword"] = getCourseID.PasswordToken.password_token.ToString();
                return RedirectToAction("Index");
            }
           // return View();
        }

        //GET: Staff/GenerateQrCode/id
        public ActionResult GenerateQrCode(int? id)
        {
            using (var db = new ProjectEntities())
            { 
                var index = db.Courses.Where(c => c.courseID == id).FirstOrDefault();
                if (index != null)
                {
                    string pageUrl = "http://localhost:59524/Logs/SignAttendance/" + id;
                    QRCodeEncoder codeEncoder = new QRCodeEncoder();
                    Bitmap bitmap = codeEncoder.Encode(pageUrl);
                    bitmap.Save($"C:\\Users\\odigietony\\source\\repos\\AttendanceWebApp\\AttendanceWebApp\\QrImage\\{index.courseID}.jpg" ,ImageFormat.Jpeg);
                    var QrImage = Url.Content($"~/QrImage/{index.courseID}.jpg");
                    ViewData["QrImage"] = QrImage;
                }
                return View("GenerateQrCode");
            } 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }


}

AttendanceWebApp/AttendanceWebApp/Views/Shared/LogOff.cshtml
@model AttendanceWebApp.Models.Course
 
@if (@Session["Name"] != null)
{
    using (Html.BeginForm("LogOff", "Staff", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, @Session["Name"]!
                </a>    
                <div class="dropdown-menu" aria-labelledby="navbarDropdown"> 
                    <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                </div>
            </li> 
        </ul>
    }
}
else
{
     <li >@Html.ActionLink("Log in", "Login", "Staff", routeValues: null, htmlAttributes: new { @style = "color:#C0C0C0"  })</li>
     
}

 

AttendanceWebApp/AttendanceWebApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/mdb.css" rel="stylesheet" />
    <link href="~/Content/mdb.min.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link href="~/Content/css/all.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/mdb.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-nav navbar-expand-md navbar-dark fixed-top ">
        <div class="container">
            <a href="#" class="navbar-brand">
                @Html.ActionLink("Attendance Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav">
                    <li class="nav-item nav-link ml-5">@Html.ActionLink("Home", "Index", "Admin", null, new { @style = "color:#ffffff" })</li>
                    <li class="nav-item dropdown ml-5">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Registration</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("StaffRegistration", "Admin")"> Staff Registration</a>
                            <a class="dropdown-item" href="@Url.Action("StudentRegistration", "Admin")"> Student Registration </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown ml-5">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Course</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("CourseCreation", "Admin")">Add Courses</a>
                            <a class="dropdown-item" href="@Url.Action("CourseReg", "Admin")"> Assign Couses To Students</a>
                            <a class="dropdown-item" href="@Url.Action("LecturerReg", "Admin")"> Assign Staff to Courses </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown ml-5">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Logs</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Students", "Admin")">View Available Students</a>
                            <a class="dropdown-item" href="@Url.Action("StaffList", "Admin")">View Available Staff</a>
                            <a class="dropdown-item" href="@Url.Action("LecturerRegList", "Admin")">View Course and their Lecturers </a>
                            <a class="dropdown-item" href="@Url.Action("CourseRegList", "Admin")">View Students and their Course </a>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class=" view" id="admin">
        <div class="mask rgba-black-strong text-center">

            @RenderBody()
            <hr />
            <footer class="fixed-bottom">
                <p>&copy; @DateTime.Now.Year - Attendance Application</p>
            </footer>

        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper.min.js")
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/mdb.js"></script>
    <script type="text/javascript" src="~/Scripts/mdb.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceWebApp/AttendanceWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/mdb.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link href="~/Content/css/all.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/addons/datatables.css" rel="stylesheet" />
        <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />*@
    <link href="~/Content/mdb.min.css" rel="stylesheet" />
     

</head>
<body>
    <nav class="navbar navbar-nav navbar-expand-md navbar-dark fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand">
                @Html.ActionLink("Attendance Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color:#C0C0C0" })
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-md-5">
                    <li class="nav-item nav-link">@Html.ActionLink("Home", "Index", "Home", null, new { @style = "color:#C0C0C0" })</li>
                    <li class="nav-item nav-link">@Html.ActionLink("Contact", "Contact", "Home", null, new { @style = "color:#C0C0C0" })</li>
                    <li class="nav-item nav-link">@Html.ActionLink("About", "About", "Home", null, new { @style = "color:#C0C0C0" })</li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    @Html.Partial("LogOff")
                </ul>
               
            </div>
        </div>
    </nav>
    <div class="view" id="intro">
        <div class="mask rgba-black-strong text-center">
            @RenderBody()
            <hr />
            <footer class="fixed-bottom">
                <p>&copy; @DateTime.Now.Year - Attendance Application</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper.min.js")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="~/Scripts/mdb.min.js"></script> 
    <script type="text/javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceWebApp/AttendanceWebApp/Views/Shared/_StudentAttendanceLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/mdb.css" rel="stylesheet" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <link href="~/Content/css/all.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/addons/datatables.css" rel="stylesheet" />
        <link href="~/Content/addons/datatables.min.css" rel="stylesheet" />*@
    <link href="~/Content/mdb.min.css" rel="stylesheet" />


</head>
<body>
    <nav class="navbar navbar-nav navbar-expand-md navbar-dark fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand">
                @Html.ActionLink("Attendance Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color:#C0C0C0" })
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-md-5">
                    <li class="nav-item nav-link">@Html.ActionLink("Home", "Index", "Home", null, new { @style = "color:#C0C0C0" })</li>
                    <li class="nav-item nav-link">@Html.ActionLink("Contact", "Contact", "Home", null, new { @style = "color:#C0C0C0" })</li>
                    <li class="nav-item nav-link">@Html.ActionLink("About", "About", "Home", null, new { @style = "color:#C0C0C0" })</li>
                </ul> 
            </div>
        </div>
    </nav>
    <div class="view" id="intro">
        <div class="mask rgba-black-strong text-center">
            @RenderBody()
            <hr />
            <footer class="fixed-bottom">
                <p>&copy; @DateTime.Now.Year - Attendance Application</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper.min.js")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="~/Scripts/mdb.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.js"></script>
    <script type="text/javascript" src="~/Scripts/addons/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>